---

- name: Include RHEL/Centos 7 tasks
  include_tasks: redhat7.yml
  when: ansible_distribution_major_version == "7"

- name: Include RHEL/Centos 8 tasks
  include_tasks: redhat8.yml
  when: ansible_distribution_major_version == "8"
