---

# The python2 docker SDK no longer works when trying to initialise a swarm
# so we will use the python3 docker SDK

- name: python2 block
  vars:
    ansible_python_interpreter: /usr/bin/python
  block:

    - name: Remove out-dated docker software
      yum:
        name: "{{ old_docker_packages }}"
        state: absent

    - name: Install yum utils
      yum:
        name: yum-utils
        state: present

    - name: Add Docker repo GPG key
      rpm_key:
        key: "{{ docker_repo_data['gpg_key'] }}"
        state: present

    - name: Add Docker yum repository
      get_url:
        url: "{{ docker_repo_data['url'] }}"
        dest: "/etc/yum.repos.d/docker-{{ docker_edition }}.repo"
        owner: root
        group: root
        mode: "0644"

    - name: Install docker packages
      yum:
        name: "{{ docker_packages }}"
        state: present
      notify: restart_docker

    - name: Install Docker pip requirements
      vars:
        ansible_python_interpreter: /usr/bin/python3
      pip:
        name: "{{ docker_pip_packages }}"
        state: present
        executable: pip3

    - name: Enable & start docker service
      systemd:
        name: docker
        state: started
        enabled: yes
        masked: no

    - name: Display insecure registries
      debug:
        var: docker_insecure_regs
        verbosity: "{{ verbosity_level | default(1) }}"

    - name: Enable insecure registries
      template:
        src: daemon.json.j2
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: "0644"
        backup: yes
      when: docker_insecure_regs | default([]) | length
      notify: restart_docker
