---

- name: Install NFS components
  hosts: nfs
  gather_facts: no
  become: yes
  tags:
    - nfs_install
    - nfs

  tasks:

    - name: Run nfs installation role
      include_role:
        name: ansible_role_nfs_install
